FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY /Daemon/Daemon.csproj ./Daemon/
COPY /AdChannel/AdChannel.csproj ./AdChannel/

RUN dotnet restore ./Daemon/Daemon.csproj

COPY . .
RUN dotnet publish ./Daemon/Daemon.csproj -c Release -o /app/publish --no-restore

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Daemon.dll"]
