import React, { useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Input } from '../Input';
import { Checkbox } from '../Checkbox';
import { Button } from '../Button';
import { FileUpload } from '../FileUpload';
import fileIcon from '../../../icons/file-icon.svg';
import './CreateAdForm.scss';
import { apiFetch } from '../../../api';

export const CreateAdForm: React.FC = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const editId = searchParams.get('edit');
  const isEditMode = !!editId;
  const [formData, setFormData] = useState({
    productName: '',
    productPrice: '',
    productDescription: '',
    targetAge: '',
    maxAdCost: '',
    productLink: '',
    postTitle: '',
    postText: '',
    adaptForTelegram: false,
    autoGeneratePostTitle: false,
    autoGeneratePostText: false,
    autoGenerateDescription: false,
    erirDescription: '',
  });
  
  const [uploadedFiles, setUploadedFiles] = useState<File[]>([]);
  const [isGeneratingTitle, setIsGeneratingTitle] = useState(false);
  const [isGeneratingText, setIsGeneratingText] = useState(false);
  const [isGeneratingErir, setIsGeneratingErir] = useState(false);
  const [existingImageUrl, setExistingImageUrl] = useState<string | null>(null);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleCheckboxChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, checked } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: checked,
    }));

    // Автогенерация при включении чекбокса
    if (checked) {
      if (name === 'autoGeneratePostTitle' && formData.productName) {
        setIsGeneratingTitle(true);
        try {
          const result = await apiFetch<{ title: string }>('/api/ai/generate/title', {
            method: 'POST',
            body: JSON.stringify({ productName: formData.productName }),
          });
          setFormData((prev) => ({ ...prev, postTitle: result.title }));
        } catch (error) {
          console.error('Ошибка генерации заголовка:', error);
          setFormData((prev) => ({ ...prev, autoGeneratePostTitle: false }));
        } finally {
          setIsGeneratingTitle(false);
        }
      } else if (name === 'autoGeneratePostText' && formData.productName && formData.productDescription && formData.productPrice) {
        setIsGeneratingText(true);
        try {
          const result = await apiFetch<{ text: string }>('/api/ai/generate/post', {
            method: 'POST',
            body: JSON.stringify({
              productName: formData.productName,
              description: formData.productDescription,
              price: Number(formData.productPrice),
            }),
          });
          setFormData((prev) => ({ ...prev, postText: result.text }));
        } catch (error) {
          console.error('Ошибка генерации текста:', error);
          setFormData((prev) => ({ ...prev, autoGeneratePostText: false }));
        } finally {
          setIsGeneratingText(false);
        }
      } else if (name === 'autoGenerateDescription' && formData.productName && formData.productDescription) {
        setIsGeneratingErir(true);
        try {
          // Используем тот же эндпоинт для генерации, что и для поста, но можно создать отдельный
          const result = await apiFetch<{ text: string }>('/api/ai/generate/post', {
            method: 'POST',
            body: JSON.stringify({
              productName: formData.productName,
              description: formData.productDescription,
              price: Number(formData.productPrice) || 0,
            }),
          });
          setFormData((prev) => ({ ...prev, erirDescription: result.text }));
        } catch (error) {
          console.error('Ошибка генерации ЕРИР:', error);
          setFormData((prev) => ({ ...prev, autoGenerateDescription: false }));
        } finally {
          setIsGeneratingErir(false);
        }
      }
    }
  };

  const handleFileSelect = (files: FileList | null) => {
    if (files) {
      const fileArray = Array.from(files);
      setUploadedFiles((prev) => [...prev, ...fileArray]);
    }
  };
  
  const handleRemoveFile = (index: number) => {
    setUploadedFiles((prev) => prev.filter((_, i) => i !== index));
  };

  useEffect(() => {
    if (isEditMode && editId) {
      const loadCampaign = async () => {
        try {
          const campaigns = await apiFetch<any[]>('/api/ads/company/my');
          const campaign = campaigns.find(c => c.id === editId);
          if (campaign) {
            setFormData({
              productName: campaign.productName || '',
              productPrice: String(campaign.productPrice || ''),
              productDescription: campaign.productDescription || '',
              targetAge: campaign.ageOfTargetAudience || '',
              maxAdCost: String(campaign.adCost || ''),
              productLink: campaign.linkToProduct || '',
              postTitle: '',
              postText: '',
              adaptForTelegram: campaign.needAutoFormatingToTgPost || false,
              autoGeneratePostTitle: false,
              autoGeneratePostText: false,
              autoGenerateDescription: false,
              erirDescription: '',
            });
            if (campaign.imageUrl) {
              setExistingImageUrl(campaign.imageUrl);
            }
          }
        } catch (error) {
          console.error('Ошибка загрузки рекламы для редактирования:', error);
        }
      };
      loadCampaign();
    }
  }, [isEditMode, editId]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      let imageUrl: string | null = existingImageUrl;
      if (uploadedFiles.length > 0) {
        const firstFile = uploadedFiles[0];
        if (firstFile.type.startsWith('image/')) {
          const reader = new FileReader();
          imageUrl = await new Promise<string>((resolve, reject) => {
            reader.onload = (e) => resolve(e.target?.result as string);
            reader.onerror = reject;
            reader.readAsDataURL(firstFile);
          });
        }
      }

      const payload = {
        productName: formData.productName,
        productPrice: Number(formData.productPrice),
        productDescription: formData.productDescription,
        ageOfTargetAudience: formData.targetAge,
        adCost: Number(formData.maxAdCost),
        needAutoFormatingToTgPost: formData.adaptForTelegram,
        linkToProduct: formData.productLink || null,
        imageUrl: imageUrl,
        isCanceled: false,
      };

      if (isEditMode && editId) {
        await apiFetch(`/api/ads/company/${editId}`, {
          method: 'PUT',
          body: JSON.stringify(payload),
        });
        localStorage.setItem('showAdCreatedNotification', 'true');
      } else {
        await apiFetch('/api/ads/create', {
          method: 'POST',
          body: JSON.stringify(payload),
        });
        localStorage.setItem('showAdCreatedNotification', 'true');
      }

      navigate('/account');
    } catch (error) {
      console.error('Ошибка при сохранении рекламы', error);
    }
  };

  return (
    <form className="create-ad-form" onSubmit={handleSubmit}>
      <h1 className="create-ad-form__title">{isEditMode ? 'Редактировать рекламный креатив' : 'Создать рекламный креатив'}</h1>

      <div className="create-ad-form__field">
        <label htmlFor="productName" className="create-ad-form__label">
          Название продукта *
        </label>
        <Input
          type="text"
          id="productName"
          name="productName"
          value={formData.productName}
          onChange={handleInputChange}
          placeholder="Введите название продукта"
          required
        />
      </div>

      <div className="create-ad-form__field">
        <label htmlFor="productPrice" className="create-ad-form__label">
          Цена продукта *
        </label>
        <Input
          type="number"
          id="productPrice"
          name="productPrice"
          value={formData.productPrice}
          onChange={handleInputChange}
          placeholder="Введите цену"
          required
        />
      </div>

      <div className="create-ad-form__field">
        <label htmlFor="productDescription" className="create-ad-form__label">
          Описание продукта *
        </label>
        <textarea
          id="productDescription"
          name="productDescription"
          className="create-ad-form__textarea"
          value={formData.productDescription}
          onChange={(e) =>
            setFormData((prev) => ({ ...prev, productDescription: e.target.value }))
          }
          placeholder="Введите описание продукта"
          rows={5}
          required
        />
      </div>

      <div className="create-ad-form__field">
        <label htmlFor="targetAge" className="create-ad-form__label">
          Возраст таргетной аудитории *
        </label>
        <Input
          type="text"
          id="targetAge"
          name="targetAge"
          value={formData.targetAge}
          onChange={handleInputChange}
          placeholder="Например: 18-35"
          required
        />
      </div>

      <div className="create-ad-form__field">
        <label htmlFor="maxAdCost" className="create-ad-form__label">
          Максимальная стоимость за рекламу *
        </label>
        <Input
          type="number"
          id="maxAdCost"
          name="maxAdCost"
          value={formData.maxAdCost}
          onChange={handleInputChange}
          placeholder="Введите максимальную стоимость"
          required
        />
      </div>

      <div className="create-ad-form__field">
        <label htmlFor="productLink" className="create-ad-form__label">
          Ссылка на товар/услугу (необязательно)
        </label>
        <Input
          type="text"
          id="productLink"
          name="productLink"
          value={formData.productLink}
          onChange={handleInputChange}
          placeholder="https://"
        />
      </div>

      <div className="create-ad-form__field">
        <label className="create-ad-form__label">Заголовок поста</label>
        <div className="create-ad-form__checkbox-wrapper">
          <Checkbox
            id="autoGeneratePostTitle"
            name="autoGeneratePostTitle"
            checked={formData.autoGeneratePostTitle}
            onChange={handleCheckboxChange}
            label="Сформировать автоматически"
          />
        </div>
        {formData.autoGeneratePostTitle ? (
          <div className="create-ad-form__generated-content">
            <div className="create-ad-form__generated-label">Сгенерированный заголовок:</div>
            {isGeneratingTitle ? (
              <div className="create-ad-form__generating">Генерация заголовка...</div>
            ) : (
              <div className="create-ad-form__generated-text">
                {formData.postTitle || 'Заголовок не сгенерирован'}
              </div>
            )}
          </div>
        ) : (
          <Input
            type="text"
            id="postTitle"
            name="postTitle"
            value={formData.postTitle}
            onChange={handleInputChange}
            placeholder="Заголовок"
            required
            className="create-ad-form__input-after-checkbox"
          />
        )}
      </div>

      <div className="create-ad-form__field">
        <label className="create-ad-form__label">Текст поста</label>
        <div className="create-ad-form__checkbox-wrapper">
          <Checkbox
            id="autoGeneratePostText"
            name="autoGeneratePostText"
            checked={formData.autoGeneratePostText}
            onChange={handleCheckboxChange}
            label="Сформировать автоматически"
          />
        </div>
        {formData.autoGeneratePostText ? (
          <div className="create-ad-form__generated-content">
            <div className="create-ad-form__generated-label">Сгенерированный текст поста:</div>
            {isGeneratingText ? (
              <div className="create-ad-form__generating">Генерация текста поста...</div>
            ) : (
              <div className="create-ad-form__generated-text">
                {formData.postText || 'Текст не сгенерирован'}
              </div>
            )}
          </div>
        ) : (
          <textarea
            id="postText"
            name="postText"
            className="create-ad-form__textarea create-ad-form__textarea--after-checkbox"
            value={formData.postText}
            onChange={(e) =>
              setFormData((prev) => ({ ...prev, postText: e.target.value }))
            }
            placeholder="Введите текст поста"
            rows={5}
            required
          />
        )}
        <div className="create-ad-form__checkbox-wrapper">
          <Checkbox
            id="adaptForTelegram"
            name="adaptForTelegram"
            checked={formData.adaptForTelegram}
            onChange={handleCheckboxChange}
            label="Адаптировать текст под телеграм-канал"
          />
        </div>
      </div>

      <div className="create-ad-form__field">
        <label className="create-ad-form__label">
          Фото и видео (необязательно)
        </label>
        <FileUpload onFileSelect={handleFileSelect} />
        {uploadedFiles.length > 0 && (
          <div className="create-ad-form__files">
            {uploadedFiles.map((file, index) => (
              <div key={index} className="create-ad-form__file-item">
                <img
                  src={fileIcon}
                  alt="File icon"
                  className="create-ad-form__file-icon"
                />
                <span className="create-ad-form__file-name">{file.name}</span>
                <button
                  type="button"
                  className="create-ad-form__file-remove"
                  onClick={() => handleRemoveFile(index)}
                >
                  ×
                </button>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="create-ad-form__field">
        <label className="create-ad-form__label">Описание для ЕРИР</label>
        <div className="create-ad-form__checkbox-wrapper">
          <Checkbox
            id="autoGenerateDescription"
            name="autoGenerateDescription"
            checked={formData.autoGenerateDescription}
            onChange={handleCheckboxChange}
            label="Сформировать автоматически"
          />
        </div>
        {formData.autoGenerateDescription ? (
          <div className="create-ad-form__generated-content create-ad-form__generated-content--erir">
            <div className="create-ad-form__generated-label create-ad-form__generated-label--erir">Сгенерированное описание для ЕРИР:</div>
            {isGeneratingErir ? (
              <div className="create-ad-form__generating create-ad-form__generating--erir">Генерация описания...</div>
            ) : (
              <div className="create-ad-form__generated-text">
                {formData.erirDescription || 'Описание не сгенерировано'}
              </div>
            )}
          </div>
        ) : (
          <textarea
            id="erirDescription"
            name="erirDescription"
            className="create-ad-form__textarea create-ad-form__textarea--erir create-ad-form__textarea--after-checkbox"
            value={formData.erirDescription}
            onChange={(e) =>
              setFormData((prev) => ({ ...prev, erirDescription: e.target.value }))
            }
            placeholder="Введите описание для ЕРИР"
            rows={5}
            required
          />
        )}
      </div>

      <div className="create-ad-form__actions">
        <Button type="submit" variant="primary">
          Продолжить
        </Button>
        <a href="/account" className="create-ad-form__link">
          Перейти в личный кабинет
        </a>
      </div>
    </form>
  );
};

