import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Input } from '../Input';
import { Checkbox } from '../Checkbox';
import { Button } from '../Button';
import { FileUpload } from '../FileUpload';
import fileIcon from '../../../icons/file-icon.svg';
import './CreateAdForm.scss';

export const CreateAdForm: React.FC = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    productName: '',
    productPrice: '',
    productDescription: '',
    targetAge: '',
    maxAdCost: '',
    productLink: '',
    postTitle: '',
    postText: '',
    adaptForTelegram: false,
    autoGeneratePostTitle: false,
    autoGeneratePostText: false,
    autoGenerateDescription: false,
    erirDescription: '',
  });
  
  const [uploadedFiles, setUploadedFiles] = useState<File[]>([]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleCheckboxChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, checked } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: checked,
    }));
  };

  const handleFileSelect = (files: FileList | null) => {
    if (files) {
      const fileArray = Array.from(files);
      setUploadedFiles((prev) => [...prev, ...fileArray]);
    }
  };
  
  const handleRemoveFile = (index: number) => {
    setUploadedFiles((prev) => prev.filter((_, i) => i !== index));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // TODO: Здесь будет отправка данных на бэкенд
    // const response = await fetch('/api/ads', {
    //   method: 'POST',
    //   body: JSON.stringify(formData),
    // });
    
    // Сохраняем флаг для показа уведомления
    localStorage.setItem('showAdCreatedNotification', 'true');
    
    // Перенаправляем в личный кабинет
    navigate('/account');
  };

  return (
    <form className="create-ad-form" onSubmit={handleSubmit}>
      <h1 className="create-ad-form__title">Создать рекламный креатив</h1>

      <div className="create-ad-form__field">
        <label htmlFor="productName" className="create-ad-form__label">
          Название продукта *
        </label>
        <Input
          type="text"
          id="productName"
          name="productName"
          value={formData.productName}
          onChange={handleInputChange}
          placeholder="Введите название продукта"
          required
        />
      </div>

      <div className="create-ad-form__field">
        <label htmlFor="productPrice" className="create-ad-form__label">
          Цена продукта *
        </label>
        <Input
          type="number"
          id="productPrice"
          name="productPrice"
          value={formData.productPrice}
          onChange={handleInputChange}
          placeholder="Введите цену"
          required
        />
      </div>

      <div className="create-ad-form__field">
        <label htmlFor="productDescription" className="create-ad-form__label">
          Описание продукта *
        </label>
        <textarea
          id="productDescription"
          name="productDescription"
          className="create-ad-form__textarea"
          value={formData.productDescription}
          onChange={(e) =>
            setFormData((prev) => ({ ...prev, productDescription: e.target.value }))
          }
          placeholder="Введите описание продукта"
          rows={5}
          required
        />
      </div>

      <div className="create-ad-form__field">
        <label htmlFor="targetAge" className="create-ad-form__label">
          Возраст таргетной аудитории *
        </label>
        <Input
          type="text"
          id="targetAge"
          name="targetAge"
          value={formData.targetAge}
          onChange={handleInputChange}
          placeholder="Например: 18-35"
          required
        />
      </div>

      <div className="create-ad-form__field">
        <label htmlFor="maxAdCost" className="create-ad-form__label">
          Максимальная стоимость за рекламу *
        </label>
        <Input
          type="number"
          id="maxAdCost"
          name="maxAdCost"
          value={formData.maxAdCost}
          onChange={handleInputChange}
          placeholder="Введите максимальную стоимость"
          required
        />
      </div>

      <div className="create-ad-form__field">
        <label htmlFor="productLink" className="create-ad-form__label">
          Ссылка на товар/услугу (необязательно)
        </label>
        <Input
          type="text"
          id="productLink"
          name="productLink"
          value={formData.productLink}
          onChange={handleInputChange}
          placeholder="https://"
        />
      </div>

      <div className="create-ad-form__field">
        <label className="create-ad-form__label">Заголовок поста</label>
        <div className="create-ad-form__checkbox-wrapper">
          <Checkbox
            id="autoGeneratePostTitle"
            name="autoGeneratePostTitle"
            checked={formData.autoGeneratePostTitle}
            onChange={handleCheckboxChange}
            label="Сформировать автоматически"
          />
        </div>
        {!formData.autoGeneratePostTitle && (
          <Input
            type="text"
            id="postTitle"
            name="postTitle"
            value={formData.postTitle}
            onChange={handleInputChange}
            placeholder="Заголовок"
            required
            className="create-ad-form__input-after-checkbox"
          />
        )}
      </div>

      <div className="create-ad-form__field">
        <label className="create-ad-form__label">Текст поста</label>
        <div className="create-ad-form__checkbox-wrapper">
          <Checkbox
            id="autoGeneratePostText"
            name="autoGeneratePostText"
            checked={formData.autoGeneratePostText}
            onChange={handleCheckboxChange}
            label="Сформировать автоматически"
          />
        </div>
        {!formData.autoGeneratePostText && (
          <textarea
            id="postText"
            name="postText"
            className="create-ad-form__textarea create-ad-form__textarea--after-checkbox"
            value={formData.postText}
            onChange={(e) =>
              setFormData((prev) => ({ ...prev, postText: e.target.value }))
            }
            placeholder="Введите текст поста"
            rows={5}
            required
          />
        )}
        <div className="create-ad-form__checkbox-wrapper">
          <Checkbox
            id="adaptForTelegram"
            name="adaptForTelegram"
            checked={formData.adaptForTelegram}
            onChange={handleCheckboxChange}
            label="Адаптировать текст под телеграм-канал"
          />
        </div>
      </div>

      <div className="create-ad-form__field">
        <label className="create-ad-form__label">
          Фото и видео (необязательно)
        </label>
        <FileUpload onFileSelect={handleFileSelect} />
        {uploadedFiles.length > 0 && (
          <div className="create-ad-form__files">
            {uploadedFiles.map((file, index) => (
              <div key={index} className="create-ad-form__file-item">
                <img
                  src={fileIcon}
                  alt="File icon"
                  className="create-ad-form__file-icon"
                />
                <span className="create-ad-form__file-name">{file.name}</span>
                <button
                  type="button"
                  className="create-ad-form__file-remove"
                  onClick={() => handleRemoveFile(index)}
                >
                  ×
                </button>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="create-ad-form__field">
        <label className="create-ad-form__label">Описание для ЕРИР</label>
        <div className="create-ad-form__checkbox-wrapper">
          <Checkbox
            id="autoGenerateDescription"
            name="autoGenerateDescription"
            checked={formData.autoGenerateDescription}
            onChange={handleCheckboxChange}
            label="Сформировать автоматически"
          />
        </div>
        {!formData.autoGenerateDescription && (
          <textarea
            id="erirDescription"
            name="erirDescription"
            className="create-ad-form__textarea create-ad-form__textarea--erir create-ad-form__textarea--after-checkbox"
            value={formData.erirDescription}
            onChange={(e) =>
              setFormData((prev) => ({ ...prev, erirDescription: e.target.value }))
            }
            placeholder="Введите описание для ЕРИР"
            rows={5}
            required
          />
        )}
      </div>

      <div className="create-ad-form__actions">
        <Button type="submit" variant="primary">
          Продолжить
        </Button>
        <a href="/account" className="create-ad-form__link">
          Перейти в личный кабинет
        </a>
      </div>
    </form>
  );
};

